# Generated by Django 3.0.7 on 2022-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintGCN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('avatar', models.ImageField(upload_to='newsPhoto', verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=548, verbose_name='Коментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен комментария')),
                ('avatar', models.ImageField(blank=True, upload_to='newCommentPhoto', verbose_name='Фото комментария')),
                ('moder_state', models.BooleanField(blank=True, default=False, verbose_name='Проверил')),
                ('complaint_quantity', models.SmallIntegerField(blank=True, default=0, verbose_name='кол-во жалоб')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['date_added'],
            },
        ),
    ]
