# Generated by Django 3.0.7 on 2022-08-31 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='newcomment',
            name='new_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.New', verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='complaintgcn',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewComment', verbose_name='Коментарий'),
        ),
        migrations.AddField(
            model_name='complaintgcn',
            name='user_complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор_ж_к_н'),
        ),
    ]
